watergis/maplibre-gl-export

README.md, example/index.js, example/index2.html, lib/export-control.ts, lib/local/en.ts, lib/local/fr.ts, lib/local/index.ts
Add an option for change the language, I added the french translation and set the english one in default
=> add translation in french

lib/export-control.ts, lib/local/fi.ts, lib/local/index.ts, lib/local/sv.ts
Added translations for Finnish and Swedish
- [x ] Adding a feature
=> Added translations for Finnish and Swedish

lib/export-control.ts
=> fixed bug of issue#8

lib/export-control.ts, lib/map-generator.ts, package.json, tsconfig.json, yarn.lock
=> upgraded to maplibre v2

README.md
Updated language documentation for Finnish and Swedish 
=> Fi sv translation documentation

README.md, lib/export-control.ts, lib/local/es.ts, lib/local/index.ts
Translate spanish.
- [ x ] Adding a feature
- [ x ] Code is up-to-date with the `main` branch
=> feat: Translate spanish

example/index2.html, webpack.cdn.config.js
=> fix: removed namespace from CDN

example/index.js, lib/map-generator.ts, package.json, yarn.lock
deleted fabric and file-server from dependencies
=> deleted fabric and file-server from dependencies

README.md, lib/export-control.ts, lib/local/de.ts, lib/local/index.ts
- FEATURE: Add German translation
=> Adding German translation

.changeset/six-bags-matter.md, .github/workflows/build.yml, .github/workflows/release.yml
=> fixed release CI and bug of demo page settings

.changeset/afraid-poems-run.md, packages/maplibre-gl-export/package.json
=> fix: added exports for maplibre-gl-export.css

.changeset/popular-numbers-juggle.md, packages/maplibre-gl-export/package.json, packages/maplibre-gl-export/src/lib/export-control.ts, packages/maplibre-gl-export/src/lib/map-generator.ts, packages/maplibre-gl-export/src/scss/maplibre-gl-export.scss, packages/maplibre-gl-export/tsconfig.json, pnpm-lock.yaml
This PR contains a breaking change.
upgraded maplibre to v3 now.
also, updated other npm packages in the repo.
This PR is also going to delete a code added by https://github.com/watergis/maplibre-gl-export/pull/18 by @21601-kimura. The code occurs an error since maplibre v3. It looks working without that code. let's see!
=> feat: upgraded maplibre-gl-js to v3

packages/maplibre-gl-export/README.md
Update of the example code and the version for the CDN
=> Update readme for CDN usage

renovate.json
=> add settings to renovate.json

sites/demo/src/routes/(doc)/+page.svelte
=> doc: improved documentation

sites/demo/src/app.html, sites/demo/src/routes/(doc)/+layout.svelte, sites/demo/src/routes/(doc)/+page.svelte, sites/demo/tailwind.config.ts
=> fix: adjust image size and changed theme

packages/mapbox-gl-export/index_cdn.html, packages/mapbox-gl-export/index_cdn.js, packages/maplibre-gl-export/index_cdn.html
=> added html for testing cdn

sites/demo/src/lib/Navigation.svelte, sites/demo/src/routes/(doc)/+layout.svelte, sites/demo/src/routes/(doc)/+page.svelte
=> fix: responsive

packages/mapbox-gl-export/README.md, packages/maplibre-gl-export/README.md
=> doc: updated readme for CDN usage

.changeset/famous-dodos-invite.md, packages/maplibre-gl-export/src/lib/map-generator-base.ts
=> refactor: removed unused variable from MapGeneratorBase class

.changeset/breezy-ghosts-sparkle.md, packages/maplibre-gl-export/src/lib/map-generator.ts
I realized the code now can work. I enabled the code adding image again.
=> fix: enabled addImage code for maplibre-gl-export again

.changeset/unlucky-otters-unite.md, packages/maplibre-gl-export/src/lib/interfaces/Language.ts, sites/demo/src/lib/LanguageSelector.svelte
=> refactor: export AvailableLanguages as an array from mapblire-gl-export

packages/maplibre-gl-export/src/lib/local/pt.ts
I added a Portuguese translation file (`pt.ts`) with translations for various interface elements.
=> Addition of Portuguese Translation File (pt.ts)

.changeset/afraid-bottles-jog.md, packages/maplibre-gl-export/src/lib/local/de.ts, packages/maplibre-gl-export/src/lib/local/es.ts, packages/maplibre-gl-export/src/lib/local/fi.ts, packages/maplibre-gl-export/src/lib/local/fr.ts, packages/maplibre-gl-export/src/lib/local/ja.ts, packages/maplibre-gl-export/src/lib/local/sv.ts, packages/maplibre-gl-export/src/lib/local/uk.ts, packages/maplibre-gl-export/src/lib/local/vi.ts, packages/maplibre-gl-export/src/lib/local/zhHans.ts, packages/maplibre-gl-export/src/lib/local/zhHant.ts
=> fix: use local language name for Translation object

.changeset/two-peas-eat.md, packages/maplibre-gl-export/src/lib/local/ca.ts, packages/maplibre-gl-export/src/lib/local/index.ts
=> feat: add Catalan translation

sites/demo/src/routes/(doc)/+page.svelte
=> fix: fixed docs layout for responsive

.changeset/chilly-dolls-cheer.md, packages/mapbox-gl-export/src/lib/export-control.ts, packages/mapbox-gl-export/src/lib/map-generator.ts, packages/maplibre-gl-export/index.ts, packages/maplibre-gl-export/src/lib/export-control.ts, packages/maplibre-gl-export/src/lib/interfaces/ControlOptions.ts, packages/maplibre-gl-export/src/lib/map-generator-base.ts, packages/maplibre-gl-export/src/lib/map-generator.ts, sites/demo/src/routes/(doc)/+page.svelte
=> feat: export north icon as a symbol layer

.changeset/weak-plums-suffer.md, packages/mapbox-gl-export/src/lib/export-control.ts, packages/mapbox-gl-export/src/lib/map-generator.ts, packages/maplibre-gl-export/index.ts, packages/maplibre-gl-export/src/lib/export-control.ts, packages/maplibre-gl-export/src/lib/interfaces/AttributionStyle.ts, packages/maplibre-gl-export/src/lib/interfaces/ControlOptions.ts, packages/maplibre-gl-export/src/lib/map-generator-base.ts, packages/maplibre-gl-export/src/lib/map-generator.ts, sites/demo/src/routes/(doc)/+page.svelte
=> fix: add visibility and position option for attribution control.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, packages/mapbox-gl-export/CHANGELOG.md, packages/mapbox-gl-export/src/lib/map-generator.ts, packages/maplibre-gl-export/CHANGELOG.md, packages/maplibre-gl-export/src/lib/map-generator-base.ts, packages/maplibre-gl-export/src/lib/map-generator.ts, sites/demo/src/routes/(doc)/+page.svelte
Fixed a number of misspellings throughout.
=> Fixes a number of misspellings throughout.

.github/workflows/build.yml, .github/workflows/release.yml
=> chore: update node version of CI to v22 LTS
